# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-22 09:28
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('is_best_answer', models.BooleanField(default=False)),
                ('body', ckeditor.fields.RichTextField()),
                ('answered_date', models.DateTimeField(default=datetime.datetime(2021, 2, 22, 9, 28, 14, 116004, tzinfo=utc))),
                ('edited_date', models.DateTimeField(default=datetime.datetime(2021, 2, 22, 9, 28, 14, 116035, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=500)),
                ('posted_date', models.DateTimeField(default=datetime.datetime(2021, 2, 22, 9, 28, 14, 116733, tzinfo=utc))),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('votes', models.IntegerField(default=0)),
                ('answers', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('asked_date', models.DateTimeField(default=datetime.datetime(2021, 2, 22, 9, 28, 14, 114697, tzinfo=utc))),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2021, 2, 22, 9, 28, 14, 114729, tzinfo=utc))),
                ('has_best_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=555)),
                ('votes', models.IntegerField(default=0)),
                ('posted_date', models.DateTimeField(default=datetime.datetime(2021, 2, 22, 9, 28, 14, 115422, tzinfo=utc))),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
