# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-11 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210311_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='edited_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_edited_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='edited_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
