# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-25 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210222_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
