# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-11 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210311_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='edited_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_edited_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='edited_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
