# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.Answer'),
        ),
    ]
