# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-03 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interested_tags',
            field=models.ManyToManyField(null=True, to='tags.Tag'),
        ),
    ]
