# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_interested_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interested_tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
