# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-23 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20210320_2156'),
        ('accounts', '0004_auto_20210312_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ignored_tags',
            field=models.ManyToManyField(blank=True, related_name='ignored_tags', to='tags.Tag'),
        ),
    ]
