# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-05 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_ignored_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reputation',
            field=models.FloatField(default=1.0),
        ),
    ]
