# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-03 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='related_tags',
            field=models.ManyToManyField(blank=True, related_name='_tag_related_tags_+', to='tags.Tag'),
        ),
    ]
