# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-20 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
